# Generated by Django 5.2.16 on 2026-08-13 01:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apartments', '0004_apartmentviewlog'),
        ('messages_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='related_apartment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='related_messages', to='apartments.apartment', verbose_name='关联房源'),
        ),
        migrations.AlterField(
            model_name='message',
            name='type',
            field=models.CharField(choices=[('first_rejected', '首次审核驳回'), ('change_rejected', '变更审核驳回'), ('audit_approved', '审核通过'), ('system', '系统通知')], max_length=30, verbose_name='消息类型'),
        ),
    ]
