# Generated by Django 5.2.16 on 2026-08-12 08:24

from django.db import migrations
from django.utils import timezone


def add_fee_type_dicts(apps, schema_editor):
    SystemDict = apps.get_model('dicts', 'SystemDict')
    now = timezone.now()

    entries = [
        ('fee_type', 'civilian', '民用'),
        ('fee_type', 'commercial', '商用'),
        ('fee_type', 'metered', '按表计量'),
    ]
    for category, code, label in entries:
        SystemDict.objects.get_or_create(
            category=category,
            code=code,
            defaults={
                'label': label,
                'sort': 0,
                'is_active': True,
                'created_at': now,
                'updated_at': now,
            },
        )


def remove_fee_type_dicts(apps, schema_editor):
    SystemDict = apps.get_model('dicts', 'SystemDict')
    SystemDict.objects.filter(
        category='fee_type',
        code__in=['civilian', 'commercial', 'metered'],
    ).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('dicts', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(add_fee_type_dicts, remove_fee_type_dicts),
    ]
