# Generated by Django 5.2.16 on 2026-08-14 09:50

from django.db import migrations
from django.utils import timezone


def add_audit_sensitive_fields(apps, schema_editor):
    SystemDict = apps.get_model('dicts', 'SystemDict')
    now = timezone.now()

    entries = [
        ('name', '公寓名称', 1),
        ('district_id', '行政区', 2),
        ('street_id', '街道/镇', 3),
        ('detail_address', '详细地址', 4),
        ('longitude', '经度', 5),
        ('latitude', '纬度', 6),
        ('cover_image', '封面图', 7),
        ('room_types.images', '房型图片', 8),
        ('room_types.layout_type', '户型', 9),
        ('room_types.window_type', '内外窗', 10),
        ('room_types.area', '面积', 11),
    ]
    for code, label, sort in entries:
        SystemDict.objects.get_or_create(
            category='audit_sensitive_fields',
            code=code,
            defaults={
                'label': label,
                'sort': sort,
                'is_active': True,
                'created_at': now,
                'updated_at': now,
            },
        )


def remove_audit_sensitive_fields(apps, schema_editor):
    SystemDict = apps.get_model('dicts', 'SystemDict')
    SystemDict.objects.filter(
        category='audit_sensitive_fields',
        code__in=[
            'name', 'district_id', 'street_id', 'detail_address',
            'longitude', 'latitude', 'cover_image',
            'room_types.images', 'room_types.layout_type',
            'room_types.window_type', 'room_types.area',
        ],
    ).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('dicts', '0002_add_fee_type_dict'),
    ]

    operations = [
        migrations.RunPython(add_audit_sensitive_fields, remove_audit_sensitive_fields),
    ]
