# Generated by Django 5.2.16 on 2026-08-12 08:24

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apartments', '0002_remove_roomtype_orientation'),
        ('districts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='apartment',
            name='electric_fee',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='电费编码'),
        ),
        migrations.AddField(
            model_name='apartment',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True, verbose_name='纬度'),
        ),
        migrations.AddField(
            model_name='apartment',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True, verbose_name='经度'),
        ),
        migrations.AddField(
            model_name='apartment',
            name='min_area',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True, verbose_name='最小面积（缓存）'),
        ),
        migrations.AddField(
            model_name='apartment',
            name='other_fees',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='其他费用说明'),
        ),
        migrations.AddField(
            model_name='apartment',
            name='property_fee',
            field=models.IntegerField(blank=True, null=True, verbose_name='物业费（元/月）'),
        ),
        migrations.AddField(
            model_name='apartment',
            name='service_fee',
            field=models.IntegerField(blank=True, null=True, verbose_name='服务费（元/月）'),
        ),
        migrations.AddField(
            model_name='apartment',
            name='verified',
            field=models.BooleanField(default=False, verbose_name='是否认证'),
        ),
        migrations.AddField(
            model_name='apartment',
            name='water_fee',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='水费编码'),
        ),
        migrations.AddField(
            model_name='roomtype',
            name='area',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True, verbose_name='面积（㎡）'),
        ),
        migrations.AddField(
            model_name='roomtype',
            name='available_date',
            field=models.DateField(blank=True, null=True, verbose_name='可入住日期'),
        ),
        migrations.AddField(
            model_name='roomtype',
            name='orientation',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='朝向编码'),
        ),
        migrations.AddIndex(
            model_name='apartment',
            index=models.Index(fields=['min_area'], name='apartments_min_are_6d16fd_idx'),
        ),
        migrations.AddIndex(
            model_name='apartment',
            index=models.Index(fields=['verified'], name='apartments_verifie_12e393_idx'),
        ),
    ]
