# Generated by Django 5.2.16 on 2026-08-12 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apartments', '0002_remove_roomtype_orientation'),
    ]

    operations = [
        migrations.AddField(
            model_name='apartment',
            name='min_area',
            field=models.IntegerField(blank=True, null=True, verbose_name='最小面积（缓存）'),
        ),
    ]
