# Generated by Django 5.2.16 on 2026-08-13 01:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apartments', '0003_apartment_electric_fee_apartment_latitude_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApartmentViewLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('deleted_at', models.DateTimeField(blank=True, default=None, null=True, verbose_name='逻辑删除时间')),
                ('dedupe_key', models.CharField(max_length=64, verbose_name='去重键（用户 ID 或匿名 IP）')),
                ('view_date', models.DateField(verbose_name='浏览日期')),
                ('apartment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='view_logs', to='apartments.apartment', verbose_name='房源')),
            ],
            options={
                'verbose_name': '房源浏览日志',
                'verbose_name_plural': '房源浏览日志',
                'db_table': 'apartment_view_logs',
                'indexes': [models.Index(fields=['apartment', 'view_date'], name='apartment_v_apartme_a3a8d6_idx'), models.Index(fields=['view_date'], name='apartment_v_view_da_e21c05_idx')],
                'constraints': [models.UniqueConstraint(fields=('apartment', 'dedupe_key', 'view_date'), name='unique_apartment_viewer_date')],
            },
        ),
    ]
