# Generated by Django 5.2.16 on 2026-08-14 01:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apartments', '0004_apartmentviewlog'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='roomtype',
            name='orientation',
        ),
    ]
