# Generated by Django 5.2.16 on 2026-08-14 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apartments', '0005_remove_roomtype_orientation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apartment',
            name='status',
            field=models.CharField(choices=[('draft', '草稿'), ('pending_first_review', '待首次审核'), ('first_rejected', '首次审核驳回'), ('published', '已上架'), ('offline', '已下架'), ('change_reviewing', '变更审核中')], default='draft', max_length=30, verbose_name='状态'),
        ),
    ]
