# Generated by Django 5.2.16 on 2026-08-12 09:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MetroLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('deleted_at', models.DateTimeField(blank=True, default=None, null=True, verbose_name='逻辑删除时间')),
                ('name', models.CharField(max_length=50, verbose_name='线路名称')),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='线路编码')),
                ('sort', models.IntegerField(default=0, verbose_name='排序')),
            ],
            options={
                'verbose_name': '地铁线路',
                'verbose_name_plural': '地铁线路',
                'db_table': 'metro_lines',
                'ordering': ['sort', 'id'],
            },
        ),
        migrations.CreateModel(
            name='MetroStation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('deleted_at', models.DateTimeField(blank=True, default=None, null=True, verbose_name='逻辑删除时间')),
                ('name', models.CharField(max_length=100, verbose_name='站点名称')),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=10, verbose_name='经度')),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=10, verbose_name='纬度')),
                ('sort', models.IntegerField(default=0, verbose_name='排序')),
                ('line', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stations', to='metro.metroline', verbose_name='所属线路')),
            ],
            options={
                'verbose_name': '地铁站点',
                'verbose_name_plural': '地铁站点',
                'db_table': 'metro_stations',
                'ordering': ['sort', 'id'],
            },
        ),
    ]
